#THis will deploy the safe,secure and tested App to production server.

name: Deploy to Production

on: 
    workflow_call:

jobs:

    deploytoProd:
        env:
          DOCKER_USER: ${{vars.DOCKER_USERNAME}}
          DOCKER_TAG: ${{github.sha}}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Connect to prod server 
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_KEY }}
                script: |
                    echo "Configure Deployment........."
                    mkdir -p pipeline
                    sudo apt-get update
                    sudo apt install docker-compose-v2 -y

            - name: Copy the dockercompose file
              uses: appleboy/scp-action@v1
              with: 
                    host: ${{ secrets.EC2_HOST }}
                    username: ${{ secrets.EC2_USERNAME }}
                    key: ${{ secrets.EC2_KEY }}
                    source: "docker-compose.yml"
                    target: "~/pipeline"


            - name: Start the application
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_KEY }}
                script: |
                  export DOCKER_USER="${{ vars.DOCKER_USERNAME }}"
                  export DOCKER_TOKEN="${{ secrets.DOCKER_TOKEN }}"
                  export DOCKER_TAG="${{ github.sha }}"
                  cd ~/pipeline
                  echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{vars.DOCKER_USERNAME}} --password-stdin
                  docker compose down
                  docker compose up --force-recreate -d --build --pull always
                




                  

              














                

               
       
