#THis will deploy the safe,secure and tested App to production server.

name: Deploy to Production

on: 
    workflow_call:

jobs:

    deploytoProd:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Connect to prod server
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_KEY }}
                script: |
                    echo "Starting Deployment........."
                    mkdir -p pipeline
                    pwd

            - name: Copy the dockercompose file
              uses: appleboy/scp-action@v1
              with: 
                    host: ${{ secrets.EC2_HOST }}
                    username: ${{ secrets.EC2_USERNAME }}
                    key: ${{ secrets.EC2_KEY }}
                    source: "docker-compose.yml"
                    target: "~/pipeline"

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt install docker-compose -y
            
            - name: Start the application
              run: docker compose up --force-recreate -d --build --pull always













                

               
       
