name: DOcker lint

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Validate docker fie
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
