name: Docker image scan

on:
  workflow_call:

jobs:
  validateImg:
    runs-on: ubuntu-latest
    steps:
      - name: login to dockerhub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'docker.io/${{ vars.DOCKER_USERNAME }}/github-actions-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
